// Supported Regional and International Languages configuration for HomeworkZone

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', ttsLang: 'en-US', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', ttsLang: 'hi-IN', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', ttsLang: 'ta-IN', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', ttsLang: 'te-IN', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', ttsLang: 'kn-IN', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', ttsLang: 'mr-IN', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', ttsLang: 'bn-IN', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', ttsLang: 'gu-IN', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', ttsLang: 'ml-IN', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', ttsLang: 'pa-IN', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', ttsLang: 'ur-PK', flag: '🇵🇰' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', ttsLang: 'or-IN', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', ttsLang: 'as-IN', flag: '🇮🇳' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', ttsLang: 'sa-IN', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', ttsLang: 'ne-NP', flag: '🇳🇵' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', ttsLang: 'si-LK', flag: '🇱🇰' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', ttsLang: 'es-ES', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', ttsLang: 'fr-FR', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', ttsLang: 'de-DE', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', ttsLang: 'it-IT', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', ttsLang: 'pt-PT', flag: '🇵🇹' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', ttsLang: 'nl-NL', flag: '🇳🇱' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', ttsLang: 'ru-RU', flag: '🇷🇺' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', ttsLang: 'pl-PL', flag: '🇵🇱' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', ttsLang: 'uk-UA', flag: '🇺🇦' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', ttsLang: 'tr-TR', flag: '🇹🇷' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', ttsLang: 'el-GR', flag: '🇬🇷' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', ttsLang: 'sv-SE', flag: '🇸🇪' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', ttsLang: 'no-NO', flag: '🇳🇴' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', ttsLang: 'da-DK', flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', ttsLang: 'fi-FI', flag: '🇫🇮' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文', ttsLang: 'zh-CN', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', ttsLang: 'zh-TW', flag: '🇹🇼' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', ttsLang: 'ja-JP', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', ttsLang: 'ko-KR', flag: '🇰🇷' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', ttsLang: 'id-ID', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', ttsLang: 'ms-MY', flag: '🇲🇾' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', ttsLang: 'vi-VN', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', ttsLang: 'th-TH', flag: '🇹🇭' },
  { code: 'tl', name: 'Filipino / Tagalog', nativeName: 'Tagalog', ttsLang: 'fil-PH', flag: '🇵🇭' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', ttsLang: 'ar-SA', flag: '🇸🇦' },
  { code: 'fa', name: 'Persian / Farsi', nativeName: 'فارسی', ttsLang: 'fa-IR', flag: '🇮🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', ttsLang: 'he-IL', flag: '🇮🇱' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', ttsLang: 'sw-KE', flag: '🇰🇪' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', ttsLang: 'af-ZA', flag: '🇿🇦' }
];

export const getLanguageObj = (code) => {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
};
